name: repo_auth
description: repo_auth
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:

  flutter:
    sdk: flutter
  firebase_auth:
  firebase_core:
  flutter_facebook_auth:
  google_sign_in:
  crypto:
  sign_in_with_apple:
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
